nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173']  # Allow your frontend's origin
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
        max_age: 3600
    paths:
        '^/api/':  # Apply this configuration to all routes starting with /api/
            allow_origin: ['http://localhost:5173']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
            allow_headers: ['Content-Type', 'Authorization']